import type { MachineId, MachineRuntime } from "@/types/factory";

const BASELINE_MS = 60 * 60 * 1000;

export function createInitialMachines(): Record<MachineId, MachineRuntime> {
  return {
    "CNC-01": {
      id: "CNC-01",
      name: "Primary machining center",
      kind: "CNC",
      status: "RUNNING",
      telemetry: { kind: "CNC", spindleRpm: 8012, spindleLoad: 66, temperature: 47.8, cycleTime: 8 },
      currentPartId: null,
      progress: 0,
      nominalCycle: 8,
      partsProduced: 322,
      faultsToday: 1,
      scheduledMs: BASELINE_MS,
      runningMs: BASELINE_MS * 0.94,
      baselineAvailability: 94,
      activeFaultCode: null,
    },
    "CNC-02": {
      id: "CNC-02",
      name: "Finishing machining center",
      kind: "CNC",
      status: "RUNNING",
      telemetry: { kind: "CNC", spindleRpm: 7940, spindleLoad: 61, temperature: 46.2, cycleTime: 7 },
      currentPartId: null,
      progress: 0,
      nominalCycle: 7,
      partsProduced: 319,
      faultsToday: 2,
      scheduledMs: BASELINE_MS,
      runningMs: BASELINE_MS * 0.91,
      baselineAvailability: 91,
      activeFaultCode: null,
    },
    "ROBOT-01": {
      id: "ROBOT-01",
      name: "Six-axis material handler",
      kind: "ROBOT",
      status: "RUNNING",
      telemetry: { kind: "ROBOT", jointSpeed: 42, cycleProgress: 0, gripperClosed: false, temperature: 38.4 },
      currentPartId: null,
      progress: 0,
      nominalCycle: 3,
      partsProduced: 318,
      faultsToday: 0,
      scheduledMs: BASELINE_MS,
      runningMs: BASELINE_MS * 0.97,
      baselineAvailability: 97,
      activeFaultCode: null,
    },
    "CMM-01": {
      id: "CMM-01",
      name: "Coordinate inspection cell",
      kind: "CMM",
      status: "RUNNING",
      telemetry: {
        kind: "CMM",
        inspectionProgress: 0,
        currentPart: null,
        lastResult: "PASS",
        totalInspected: 318,
        rejectionCount: 6,
      },
      currentPartId: null,
      progress: 0,
      nominalCycle: 5,
      partsProduced: 318,
      faultsToday: 0,
      scheduledMs: BASELINE_MS,
      runningMs: BASELINE_MS * 0.96,
      baselineAvailability: 96,
      activeFaultCode: null,
    },
  };
}
