"use client";

import { Activity, Box, Clock3, Gauge, Network, ShieldCheck } from "lucide-react";
import {
  Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis,
} from "recharts";
import { EventLog } from "@/components/ui/EventLog";
import { PRODUCT_DEFINITIONS } from "@/lib/simulation/productMix";
import { useFactoryStore } from "@/store/useFactoryStore";

const tooltipStyle = { background: "#121c24", border: "1px solid rgba(153,177,194,.25)", borderRadius: 7, fontSize: 10 };

export function Dashboard() {
  const kpis = useFactoryStore((state) => state.kpis);
  const chartData = useFactoryStore((state) => state.chartData);
  const productCounts = useFactoryStore((state) => state.counters.productCounts);
  const data = chartData.length ? chartData : [{ label: "Now", throughput: kpis.throughput, oee: Number(kpis.oee.toFixed(1)) }];
  const utilization = Object.entries(kpis.utilization).map(([machine, value]) => ({ machine, value: Number(value.toFixed(1)) }));
  const productMix = PRODUCT_DEFINITIONS.map((product) => ({
    product: product.shortLabel,
    completed: productCounts[product.id],
    target: Math.round(product.targetShare * kpis.partsProduced),
  }));
  const cards = [
    { label: "OEE", value: `${kpis.oee.toFixed(1)}%`, note: "Composite effectiveness", icon: Gauge },
    { label: "Throughput", value: `${Math.round(kpis.throughput)}/hr`, note: "Rolling 60 seconds", icon: Activity },
    { label: "Scrap rate", value: `${kpis.scrapRate.toFixed(1)}%`, note: `${kpis.quality.toFixed(1)}% first-pass yield`, icon: ShieldCheck },
    { label: "Parts produced", value: kpis.partsProduced.toLocaleString(), note: "Accepted assemblies", icon: Box },
    { label: "Machines online", value: `${kpis.machinesOnline} / 4`, note: "Production assets", icon: Network },
    { label: "Average cycle", value: `${kpis.averageCycleTime.toFixed(1)}s`, note: "End-to-end processing", icon: Clock3 },
  ];
  return (
    <section className="content-view" aria-labelledby="dashboard-title">
      <header className="content-header"><div><p className="eyebrow">Live manufacturing analytics</p><h1 className="section-heading" id="dashboard-title">Production dashboard</h1><p className="section-subtitle">Every metric is calculated from equipment runtime, completed cycles, and inspection events generated by the active cell simulation.</p></div><div className="status-pill status-RUNNING"><span className="live-dot" /> Live data</div></header>
      <div className="content-grid kpi-grid">
        {cards.map(({ label, value, note, icon: Icon }) => <article className="kpi-card glass-panel" key={label}><div className="panel-head"><span className="metric-label">{label}</span><Icon size={15} color="var(--blue)" /></div><div className="metric-value">{value}</div><div className="delta">{note}</div></article>)}
      </div>
      <div className="content-grid analytics-grid" style={{ marginTop: 14 }}>
        <article className="chart-card glass-panel"><p className="eyebrow">Output trend</p><h2 className="chart-title">Throughput · parts per hour</h2><ResponsiveContainer width="100%" height={225}><LineChart data={data}><CartesianGrid stroke="rgba(153,177,194,.08)" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#6f828e", fontSize: 9 }} tickLine={false} axisLine={false} /><YAxis tick={{ fill: "#6f828e", fontSize: 9 }} tickLine={false} axisLine={false} width={35} /><Tooltip contentStyle={tooltipStyle} /><Line type="monotone" dataKey="throughput" stroke="#5eb7e8" strokeWidth={2} dot={false} isAnimationActive={false} /></LineChart></ResponsiveContainer></article>
        <article className="chart-card glass-panel"><p className="eyebrow">Effectiveness model</p><h2 className="chart-title">OEE composition</h2><div className="oee-breakdown">{[["Availability",kpis.availability],["Performance",kpis.performance],["Quality",kpis.quality],["OEE",kpis.oee]].map(([label,value]) => <div className="oee-factor" key={String(label)}><div className="metric-label">{label}</div><div className="metric-value">{Number(value).toFixed(1)}<small>%</small></div></div>)}</div><ResponsiveContainer width="100%" height={145}><LineChart data={data}><CartesianGrid stroke="rgba(153,177,194,.08)" vertical={false} /><XAxis dataKey="label" hide /><YAxis domain={[0,100]} tick={{ fill: "#6f828e", fontSize: 9 }} tickLine={false} axisLine={false} width={30} /><Tooltip contentStyle={tooltipStyle} /><Line type="monotone" dataKey="oee" stroke="#55d995" strokeWidth={2} dot={false} isAnimationActive={false} /></LineChart></ResponsiveContainer></article>
      </div>
      <div className="content-grid analytics-grid" style={{ marginTop: 14 }}>
        <article className="chart-card glass-panel"><p className="eyebrow">Asset health</p><h2 className="chart-title">Machine utilization</h2><ResponsiveContainer width="100%" height={230}><BarChart data={utilization} layout="vertical" margin={{ left: 4 }}><CartesianGrid stroke="rgba(153,177,194,.08)" horizontal={false} /><XAxis type="number" domain={[0,100]} tick={{ fill: "#6f828e", fontSize: 9 }} tickLine={false} axisLine={false} /><YAxis type="category" dataKey="machine" width={73} tick={{ fill: "#9cabb3", fontSize: 9 }} tickLine={false} axisLine={false} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="value" fill="#5eb7e8" radius={[0,4,4,0]} isAnimationActive={false} /></BarChart></ResponsiveContainer></article>
        <article className="chart-card glass-panel"><p className="eyebrow">Order-driven scheduler</p><h2 className="chart-title">Accepted product mix · 50 / 30 / 20 target</h2><ResponsiveContainer width="100%" height={230}><BarChart data={productMix} layout="vertical" margin={{ left: 4 }}><CartesianGrid stroke="rgba(153,177,194,.08)" horizontal={false} /><XAxis type="number" tick={{ fill: "#6f828e", fontSize: 9 }} tickLine={false} axisLine={false} /><YAxis type="category" dataKey="product" width={58} tick={{ fill: "#9cabb3", fontSize: 9 }} tickLine={false} axisLine={false} /><Tooltip contentStyle={tooltipStyle} /><Bar dataKey="target" fill="#344854" radius={[0,4,4,0]} isAnimationActive={false} /><Bar dataKey="completed" fill="#55d995" radius={[0,4,4,0]} isAnimationActive={false} /></BarChart></ResponsiveContainer></article>
      </div>
      <div className="content-grid" style={{ marginTop: 14 }}><article className="event-card glass-panel"><p className="eyebrow">MES event stream</p><h2 className="chart-title">Production event log</h2><EventLog /></article></div>
    </section>
  );
}
